version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    image: workbee/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
  frontend:
    image: workbeefrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  postgres: